WT-7292 update webhook subscribe callback definition
wisetime-io/connect-api-spec pull request #17
Opened 2019-05-30 09:54 UTC by ShansOwn

Changed errors codes and added descriptions to content for errors.

2019-05-30 09:57 UTC, vyshane requested changes
Couple of typos.

2019-05-30 09:57 UTC, vyshane commented on spec/openapi.yaml
> +                    text/plaint:
Do you mean `text/plain`?

2019-05-30 09:57 UTC, vyshane commented on spec/openapi.yaml
> +                    text/plaint:
Do you mean `text/plain`?

2019-05-30 12:24 UTC, ShansOwn commented on spec/openapi.yaml
> +                    text/plaint:
Sure. Fixed.

2019-05-30 12:24 UTC, ShansOwn commented on spec/openapi.yaml
> +                    text/plaint:
Sure. Fixed.

2019-05-30 14:20 UTC, vyshane commented
There are serious implications to changing the HTTP codes returned by connector webhooks. This means that we will need to update the connector library, create new connector builds and update every single connector currently running in production. I vote for leaving them unchanged.

2019-05-30 14:21 UTC, vyshane requested changes
Do we really want to update webhook response codes?

2019-05-30 14:25 UTC, ShansOwn commented
> Do we really want to update webhook response codes?

They've been already updated [here](https://github.com/wisetime-io/wisetime-connector-java/commit/40454a02bf8de8e4d7c21e38ef0b02e0276140c0). I've just updated the spec according to them

2019-05-30 14:36 UTC, vyshane commented
I see. We need to think this one through. @pfilippi24 will the Connect API backend keep support for old webhooks? We can't break backwards compatibility on this one without a great deal of coordination and pain.

2019-05-31 06:46 UTC, vyshane approved these changes

2019-05-31 07:33 UTC, pfilippi24 approved these changes

2019-05-31 09:45 UTC, merged